Task2
SofiaMarchinskaya/Hw1 pull request #1
Opened 2021-11-24 21:02 UTC by SofiaMarchinskaya

2021-11-25 13:51 UTC, BSCAndroid requested changes

2021-11-25 13:51 UTC, BSCAndroid commented on app/src/main/java/com/sofiamarchinskaya/hw1/MainActivity.kt
Убери лишнюю строку

2021-11-25 13:51 UTC, BSCAndroid commented on app/src/main/java/com/sofiamarchinskaya/hw1/MainActivity.kt
> +    private lateinit var share : Button
Помнишь писал про кодстайл в конце 1го задания? Тут применен?

2021-11-25 13:51 UTC, BSCAndroid commented on app/src/main/java/com/sofiamarchinskaya/hw1/MainActivity.kt
> +            type = "text/plain"
Текстовку вынеси в константы

2021-11-25 13:51 UTC, BSCAndroid commented on app/src/main/java/com/sofiamarchinskaya/hw1/MainActivity.kt
> +        val inflater = menuInflater
Зачем лишняя переменная?

2021-11-25 13:51 UTC, BSCAndroid commented on app/src/main/java/com/sofiamarchinskaya/hw1/MainActivity.kt
> +        val inflater = menuInflater
Используется только однажды, можно без нее

2021-11-25 13:51 UTC, BSCAndroid commented on app/src/main/java/com/sofiamarchinskaya/hw1/MainActivityPresenterImpl.kt
> +
отступ лишний

2021-11-25 13:51 UTC, BSCAndroid commented on app/src/main/java/com/sofiamarchinskaya/hw1/MainActivityPresenterImpl.kt
> +    override fun shareOnClick(title : String, text : String) {
Тут кодстайл применен?

2021-11-25 13:51 UTC, BSCAndroid commented on app/src/main/java/com/sofiamarchinskaya/hw1/MainActivityView.kt
> +    fun openAboutScreen()
Делай отступы между объявлениями методов

2021-11-25 13:51 UTC, BSCAndroid commented on app/src/main/res/layout/activity_about.xml
> +        android:layout_marginStart="10dp"
В ресурсы все

2021-11-25 13:51 UTC, BSCAndroid commented on app/src/main/AndroidManifest.xml
> +            android:exported="false" />
По-умолчанию и так false, не нужно указывать

2021-11-25 13:51 UTC, BSCAndroid commented on app/src/main/AndroidManifest.xml
>              android:exported="true">
А тут по умолчанию и так true, поскольку указан intent-filter, поэтому можно не указывать

2021-11-25 18:28 UTC, SofiaMarchinskaya commented on app/src/main/java/com/sofiamarchinskaya/hw1/MainActivityPresenterImpl.kt
> +    override fun shareOnClick(title : String, text : String) {
да

2021-11-26 14:40 UTC, SofiaMarchinskaya commented on app/src/main/AndroidManifest.xml
>              android:exported="true">
Среда подсказывает,что true обязательно

2021-11-26 15:06 UTC, BSCAndroid commented on app/src/main/AndroidManifest.xml
>              android:exported="true">
ок, тогда оставь

2021-11-26 15:10 UTC, merged